language: python
python:
  - "2.7"
  - "3.6"
env:
  global:
    - BOTO_CONFIG=/doesnotexist
before_install: 
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt update
  - sudo apt-get install -y libgdal-dev libgdal20 gdal-bin python-gdal python3-gdal libspatialite5 libspatialite-dev libgeos-c1v5
# command to install dependencies
install:
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install GDAL==`gdal-config --version`
  - pip install -r requirements.txt coverage
# command to run tests
script: coverage run unit_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
