language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install: 
  - sudo apt-get install -y gdal-bin
# command to install dependencies
install:
  - pip install -r requirements.txt coverage
# command to run tests
script: coverage run unit_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
